### ISSUE TITLE
Support for DSI Tetra (feature request)

### ISSUE THREAD

**Issue by dbogdanov** [eclab/edisyn#10]
I've seen DSI Prophet '08 mentioned, and I would love to control a Tetra too.

**Comment by eclab** [comment]
I can't imagine a Tetra would be difficult to whip up support for: but I do not own one.  You'd need to add the Tetra-specific NRPN options and remove the Prophet'08 ones.  Or you could give me a Tetra!  :-)  At any rate, I imagine most everything else will work cleanly; you just need to change the NRPN database and change the right widgets.

Sean
