### ISSUE TITLE
jar corrupted? jan 2020

### ISSUE THREAD

**Issue by subv0x** [eclab/edisyn#18]
don't seem to be able to run the jar here. java is installed, am i missing s'thing? 
says the jar is corrupted.

**Comment by eclab** [comment]
I have just double-checked the jar file and it is correct.  What URL are you using to download it?  What operating system are you using?

**Comment by subv0x** [comment]
hi, thanks; 
windows10. i think my java is uptodate, redownloading now. 
i have just tried to run the jar, nothing else. is that correct?

    On Tuesday, January 7, 2020, 6:09:46 AM GMT+1, Evolutionary Computation Laboratory <notifications@github.com> wrote:  
 
 I have just double-checked the jar file and it is correct. What URL are you using to download it? What operating system are you using?

**Comment by eclab** [comment]
If it says the jar file is corrupt, this suggests that the jar file didn't download properly.  Your java installation is probably just fine.

Again: can you tell me what URL you used to download the jar file?

If you have further problems, try grabbing the following zip file
	http://cs.gmu.edu/~sean/temp/edisyn.jar.zip
The jar file is inside there; perhaps that will be more successful to download.

**Comment by subv0x** [comment]
thanks! am dl'ing now. 
here's the java i re-updated:
https://java.com/en/download/win10.jsp
(seems to be java v8...)
but i now see this:
https://www.oracle.com/technetwork/java/javase/downloads/index.html#JDK13
say it is the development kit. is this the correct current download?

**Comment by subv0x** [comment]
could just be that i have the wrong version. am able to run another java app ok.

**Comment by subv0x** [comment]
nb: got the jar file here from github. waiting for install, will get back when done.

**Comment by eclab** [comment]
You don't need the development kit (JDK), the JRE will be fine.

**Comment by subv0x** [comment]
could you show me which download? (sorry...not up on java really. but do like a little app called MPC Maid) 
i think it auto-updated recently. do i need to uninstall old version? 
would assume an update/recent install would give me the latest version !

**Comment by eclab** [comment]
Again, it's likely not your Java version -- you probably have a corrupted jar download.  Try the zip file link I provided.

**Comment by subv0x** [comment]
haHA! :-D success ! fantastic. 
hey: how did you get at the Multi mode for the K1? i thought that had no sysex for that mode? 
i have made a NovationRemote mapping for K1 - nice - but couldn't do multimode. (would really like the sysex for it if it is possible). 
and i see you've done the D-110 too. great. also have that mapped up for Novation, and tried to do a Ctrlr panel for it.(in various stages of incompletion)

**Comment by subv0x** [comment]
pleased you've done D-110. please see my Ctrlr bpanelz, espc the later ones, where i got stuck/had to quit progrmmng for a while. also had a D-20 at that point, and the PG-10 (which i sold, preferring my Remote maps). the D-20 has one less stage in the envelopes, and a D-50-like upper/lower performance mode. i don't know the D-10. 
i've done the rhythm part in the Ctrlr panel as well. i think it's a global mode eg: beyond the 'patch' memories. Ctrlr allows quite a bit of manipulation with Lua, so it would be possible to have 'default reset' in case user gets lost with it. but i never got to the point where it was a 2-way editor fetching data from the unit.

**Comment by subv0x** [comment]
the temp memory areas in the D-110 are actually quite good: you can switch the unit off, and back on again, and it will come back with all edits still active. it won't refresh until you call another Patch. of course, saving is a pain: you have to save?3? times: tone/timbre/patch - by which time you will have lost any 2ndary edits you have on other tones and timbres. the tx802 also retains its edits on power down. i don't have it anymore, so i don't know how it behaves if more than one preset is in edited form.

**Comment by subv0x** [comment]
i did crash a D-110 once. required a full reset. can't remember what i did.

**Comment by eclab** [comment]
> On Jan 7, 2020, at 1:15 AM, subv0x <notifications@github.com> wrote:
> 
> pleased you've done D-110. please see my Ctrlr bpanelz, espc the later ones, where i got stuck/had to quit progrmmng for a while.

Time to take another stab at it!  You could always go for an Edisyn patch editor.

> also had a D-20 at that point, and the PG-10 (which i sold, preferring my Remote maps). the D-20 has one less stage in the envelopes, and a D-50-like upper/lower performance mode. i don't know the D-10.

The synths I have built editors for have simply been the ones I've owned for some time.  I've picked up a D-110, so there's a D-110 editor right now.  The D-10 is a somewhat different beast and so I can't straightforwardly convert the D-110 editor for the D-10 (or D-20, or D-50)....

Some other synths in my queue coming up at some point: TG-33 (half done), TG-100, FB-01, possibly MT-32.  I gave up on the Micron, which has the worst-documented sysex in the universe.

> i've done the rhythm part in the Ctrlr panel as well.

Though I've broken this rule once or twice (notably for the Drum and Effect editors for the K4), in general I tend not to build editors for any global/singleton elements of a synth: just for patches.  Sort of thought the D-110 rhythm section was less useful to customize nowadays anyway...

Sean
