### ISSUE TITLE
Praise + Kawai XD-5 question

### ISSUE THREAD

**Issue by rv0** [eclab/edisyn#19]
Hi

I wanted to take this opportunity to thank you for making such a good editor available free of charge and open source. I don't know how I only saw this a few days ago, by accident. 
The instructions are clear, the controls are very flexible and inspiring and the midi setup for flexible. Also it works perfect on my Mac (OSX 10.13.6 High Sierra)!

Edisyn supports literally all "old" synths I have that benefit from an editor.. I was using an Atari to edit those synths and today I unplugged it an put it in storage. There's only one synth missing from the list and that's the Kawai XD-5.

Are there any plans to support it? It's very similar to the K4r. I think by copying the K4R definitions, changing the sysex device ID and adding the (long) wave list (available [here](https://encyclotronic.com/synthesizers/kawai/xd-5-r287/)) about 95% of the work would be done already. 

If no plans/progress on this, I'd be glad to help with a PR. Still have some other coding projects that require attention, but I could start at least. Not a superhero in Java but if it's a matter of just adapting the K4r definitions I can get there eventually..

**Comment by rv0** [comment]
Ok, just realised one other of my favorites missing: Yamaha TG-33 / SY-22. Might not put the atari too far yet :)

**Comment by eclab** [comment]
You're in luck: I have completed a TG-33/SY22/SY35 editor, which will be in the next release.  If you need it sooner, send me email directly (sean@cs.gmu.edu).

I am unlikely to do an XD-5 editor for the simple reason that I do not have an XD-5 to test on.

Sean

**Comment by rv0** [comment]
That's great news about the upcoming editor for the TG33.
Meanwhile I'll have a try at a XD-5 editor

**Comment by eclab** [comment]
BTW, I can't find the XD-5's sysex specification anywhere.  I (of course) have the K4's spec.

**Comment by rv0** [comment]
The manual [here](https://kawaius.com/wp-content/uploads/2019/04/Kawai-XD-5-Percussion-Synthesizer-Manual.pdf) has some info (sysex header format) on page 51/52 and the full sysex spec is [here](https://kawaius.com/wp-content/uploads/2019/04/Kawai-XD-5-Wave-List.pdf).

**Comment by eclab** [comment]
The patch sysex basically looks like to the K4 sysex but with a bunch of items missing.  The kit sysex looks like an expanded version of the multimode sysex on the K4; I imagine that'd be the harder one.

**Comment by jpater** [comment]
Hi - XD-5 user here!

I see you marked this as completed, but I don't see the XD-5 on the list of supported synths. 

Grateful for any help!

**Comment by eclab** [comment]
I must have pressed the wrong button!

In short: I can't do an XD-5 realistically without having one to test long-term, and that is unlikely.  :-(  So I need to close this, how about closed as Not Planned?
