### ISSUE TITLE
FS1R?

### ISSUE THREAD

**Issue by mourendxu** [eclab/edisyn#22]
Hi, this thing looks amazing. Any chance of an editor for the Yamaha FS1R? I see you have already covered much of Yamaha's FM line.

Thank you!!

**Comment by eclab** [comment]
I would dearly love to create an editor for the FS1R.  Unfortunately, I do not own an FS1R and as a rule cannot make patch editors for machines I don't own or have on very long-term loan (developing, testing, and supporting editors requires actual hardware).

If you had an extra FS1R you would like to give me, I would build and editor for it!

**Comment by eclab** [comment]
I'm finishing an FS1R editor. When it's ready, I could throw you a copy to beta test.

**Comment by keymanpal** [comment]
ohh!! great news! More then happy to help out "Beta test" ;-) also have an FS1R.

**Comment by eclab** [comment]
I'm about to start putting out beta test versions.  Send me email at sean.luke@gmail.com.

**Comment by eclab** [comment]
There's an initial version of the FS1R editor now out in the official release.  Expect improvements to it in the near future.
