### ISSUE TITLE
DSI Prophet 12 ?

### ISSUE THREAD

**Issue by p-phillips** [eclab/edisyn#23]
Hi.

Is there any chance that the DSI Prophet 12 could be added to this ?

Pete

**Comment by eclab** [comment]
Not unless someone gives me a Prophet 12, sorry.  The Prophet 12 has a different architecture from the ’08/Mopho/Tetra, so it’d require a different (and new) patch editor.

Sean

**Comment by p-phillips** [comment]
Could I do anything to help ? I have a P12 (clearly!).  
Pete

**Comment by eclab** [comment]
Building a patch editor means requires having a unit that you can test against and later debug against and do maintenance with.  Realistically this basically means owning a unit.  So unless you wanted to gift me your synth…

On the other hand if you’re handy with Java, it would not be difficult to convert the Prophet ’08 editor into a Prophet 12 editor: the basic sysex emitting and parsing approaches for both are very similar, both use NRPN in the same basic way, and they have similar architectures though the 12 has 4 oscillators and other gizmos.  If you want to take a shot at it, I’d be glad to give some pointers.

**Comment by p-phillips** [comment]
> _So unless you wanted to gift me your synth…_

;-)

> _On the other hand if you’re handy with Java,_

I have never programmed in Java.  I have used basic, fortran, perl, python, bash, and mainly use R at the moment. So not clueless in terms of coding, but have zilch java knowledge.  I use Linux btw. 

I'd be keen to have a look to see if it was within my competency.   I had a look at the manual and assume that to start with I could create a prophet12 directory and copy the prophet8 files into there.  If you have the time to do a bit of hand-holding then I'd like to give it a go, unless you think that java experience is necessary.

**Comment by eclab** [comment]
Without Java experience, this would be really hard to do I think.
