### ISSUE TITLE
Wavestation SR

### ISSUE THREAD

**Issue by JohnBernt** [eclab/edisyn#24]
To Solo BCD not possibly.only A

Thank you for doing this editor, super.

/John

**Comment by eclab** [comment]
I did find a minor bug in the editor's soloing, but I suspect it's not what you're asking for.

1. When there's four waves (A, B, C, D) selected in the editor, soloing produces the correct output and the SR responds properly: for example, if you select Wave C and press "Mute others", then A, B, and D will be muted and C will be unmuted.

2. When there are only TWO waves selected in the editor (A and C), soloing works for A but doesn't work for C.  I've now fixed that bug and it'll be out in the next release.  But I don't think that's what your complaint was regarding.

If you cannot get soloing to work right, by any chance have you set your SR to receive sysex parameters?  Is the MIDI channel set right on the unit?

**Comment by eclab** [comment]
Lacking further input on this bug, I'm declaring it closed.
