### ISSUE TITLE
TG77

### ISSUE THREAD

**Issue by JohnBernt** [eclab/edisyn#25]
For TG77 would be great

**Comment by eclab** [comment]
I generally write editors for machines I own or have long-term access to because I have to maintain the editors.  Thus if you want me to write a TG77 editor, you'll have to gift me a TG77.

**Comment by JohnBernt** [comment]
Dear Editor

 

How many do you want.

 

So we both have a wvaestation SR then. When i try to solo BCD it dont solo

 

I try to contact Han Solo but he was away on a mission in space.

 

 

Best regards/John

 
 

Sent: Thursday, July 23, 2020 at 2:01 AM

**Comment by eclab** [comment]
Five TG77s will be sufficient. I'll look into the soloing problem on my SR.

Sean

**Comment by JohnBernt** [comment]
Dear Sean,

 

I will se what i can do SiR

 

That sounds super.

 

And thank you for your great work doing all editors for the synths.

 

/John

 
 

Sent: Thursday, July 23, 2020 at 2:57 PM
