### ISSUE TITLE
TG33 - Parameter changes sent to tones B and D have no effect

### ISSUE THREAD

**Issue by Olyche** [eclab/edisyn#28]
I can watch changes in Edisyn being reflected consistently in tones A and C (in A-B-C-D mode), but no such changes in tabs "B" or "D".  I first noticed when modifications to the Env attacks wasn't audibly making any changes, checked the UI to confirm, nope, no changes to the values when modified in Edisyn, I also tested with the level and rate scaling.  Thanks for your help and for the great editor!

**Comment by eclab** [comment]
Send me email directly (my address is on the front page of the manual) and let me get you a development version of Edisyn so we're on the same page stomping these bugs.  [Also I think some of these bugs may already be fixed in the dev version].

Sean

**Comment by Olyche** [comment]
Closed as a result of fixes made by @eclab in test builds.
