### ISSUE TITLE
Consider using structured data sources to generate synth-specific code?

### ISSUE THREAD

**Issue by therealjeffg** [eclab/edisyn#32]
This is a very cool project!

There are some sources of synth MIDI implementations in machine-readable formats, for example:

https://github.com/usercamp/midi

https://github.com/eokuwwy/open-midi-rtc-specs

It seems like edisyn wants to [tightly couple](https://github.com/eclab/edisyn/blob/master/edisyn/synth/waldorfmicrowavext/WaldorfMicrowaveXT.java#L95) the UI widget being used with the midi implementation, so just consuming the midi implementations directly and somehow guessing what the right widget is might be very difficult to get right, but it might be fun to autogenerate code from these midi specs as a starting point to make it easier for people to create new UIs.

**Comment by eclab** [comment]
It's an interesting project idea but one that's out of scope for me.  I should warn you that communication to synths is MUCH uglier than presented in the database you provided: many synths require custom pauses in the middle of transmission or at the end, or nonstandard back-and-forth in the middle of the sysex transmission (notably Casio).  Some synths have major bugs in their sysex (Venom ugh).  Plenty of synths support NRPN but not sysex (preen, futuresonus parva), or not at all (Korg Wavestate), and others do not support notions of patch transmission (Korg Microsampler for example).  And then there's the nightmare of bitpacking.  Autogeneration won't get you as far as you think.  When I build an editor, usually about 10% of the time is spent on tabulating all the parameters and building widgets for them: the rest is often spent wrestling with the synth's strange and particular transmission protocol.

**Comment by therealjeffg** [comment]
Thanks for responding - that's some great insight!
