### ISSUE TITLE
Bi-directionality ?

### ISSUE THREAD

**Issue by drowld** [eclab/edisyn#36]
How complex would it be to make it bi directional ? Since it's already sending sysex i'm curious how hard would it be to retrieve it

**Comment by eclab** [comment]
I don't understand what you mean.  Edisyn can read and write sysex files and can both send and retrieve them from your synthesizer.  Isn't that bidirectional?

**Comment by drowld** [comment]
Nope i mean that when i change something on the synth it changes on edysin

**Comment by eclab** [comment]
Edisyn already supports this for most synths which are capable of it.  Which synthesizers are you hoping Edisyn would support in this regard'

**Comment by SeanLuke** [comment]
Not hearing anything back, I'm going to close this issue.  But if you have a specific synthesizer that Edisyn's not handling in this way, let me know and I'll check.
