### ISSUE TITLE
Missing last character of sound names on Microwave XT

### ISSUE THREAD

**Issue by samstaton** [eclab/edisyn#37]
The last character of a sound name is missing when I pull a sound from the device. I think it is because the sysex is being cut off one byte early. I think on line 2411 of WaldorfMicrowaveXT.java it should be "<= 255" rather than "< 255", because it goes up to and including 255 (http://www.carbon111.com/mwxt_manual.pdf page 112). 

Apart from that, thanks for really nice software!

**Comment by eclab** [comment]
Edisyn's XT Multi editor also has the same error; though the last byte of the multi instrument sysex is "reserved" so it's not noticed.  I'll get a new version posted in a while, waiting on a major new inclusion.  In the meantime, if you would like a beta that has the fix, send me email directly at sean@cs.gmu.edu.
