### ISSUE TITLE
Yamaha TX81Z Multimode / Instrument Offset

### ISSUE THREAD

**Issue by bennniii** [eclab/edisyn#4]
aw man! i LOVE this tool! you're incredible!
found an annoying but, whatsoever – when using the Yamaha TX81Z Editor in multimode, there's an offset in the **voice** and **bank** dials... voice/bank of instrument 1 actually controls instrument 2, instrument 2 controls instrument3 and so on..

it's be incredible if you could fix this! this is by far the best editor i've stumbled upon by now. 
thanks!

**Comment by eclab** [comment]
I can nail that fast but more specifics would be useful.  Is it *only* voice bank and number that's offset?  Or all the parameters of the Instrument?  Thus, how about Max Notes?  Lowest/Highest Key?  LFO?n Etc.

Sean

**Comment by bennniii** [comment]
thanks!
just checked – it's only voice & bank number.. all others work fine :) 
will you be builing a new version for mac and providing a download? ... i'm a real novice with git and the like...

thanks again for your great work!

**Comment by eclab** [comment]
I'd be building a new version.  Another question: when does the problem occur:

	1. When making a real-time change to Edisyn's Voice Bank and Number dials
	2. When sending a patch.
	3. Both

**Comment by bennniii** [comment]
1. yes
2. no – this works!

**Comment by eclab** [comment]
Bug fixed.  I'll have a new version out probably by end of today.

Sean

**Comment by eclab** [comment]
A new version of Edisyn has been posted with the bugfix.  Let me know if it works and I'll close the issue.

**Comment by eclab** [comment]
I just posted another bugfix.  Try again.On Mar 4, 2018 11:56 AM, bennniii <notifications@github.com> wrote:yesno – this works!

**Comment by eclab** [comment]
I'm going to close this issue but if you are still having problems, just open a new one.
