### ISSUE TITLE
Send to current Patch on Casio CZ-1 not working

### ISSUE THREAD

**Issue by hiuzhiuz** [eclab/edisyn#43]
Hi there,

all the commands such as request current patch, request next patch etc. are working fine, also I'm able to send test notes. Only the send to current patch feature is not working. I tried several things, e.g. waiting some time or checking/unchecking the Casio CZ-1 box. Once I try the feature repeatedly send to current patch and play some notes, after a few not hits the synthesizer starts to make some mumbling sounds, as if something got stuck, its not only one note is ringing constantly, more like dozens at the same time. Same happens when I press send to current patch over the short cut very fast. I can't get this sound to stop, also not via send all sounds off, only way is via MIDI on/off button on the Casio CZ-1.

I downloaded Patch Base to see if this might be related to my setup, but there all commands work fine, also the parameter changes work there in real time. 

I could cross check the differences between the sysex messages being sent from Edisyn and Patch Base, but wanted to know first if this issue might already be known or even solved or if its related to some settings I still have to make on Edisyn.

Would be happy for any comments on this topic, surely I could use Patch Base as a plan B but I really like the GUI for the Casio CZ-1 from Edisyn :)

Thanks,
Michael

Edisyn is running on a mac mini, OS 11.5.2

**Comment by eclab** [comment]
CZ sysex is very, very unusual so it's possible there's a bug.  Fortunately I have a CZ-1 I can test against.  Unfortunately I can't do so for a day or two.

- Does Write to Patch... work properly?  I would be surprised to find that it did.

Contact me directly ***@***.***) and I'll send you my current working beta copy of Edisyn to try so we're on the same page. 

Sean

**Comment by eclab** [comment]
My tests on the CZ-1 suggest that Write to Patch works fine.  Have you had any further issues?

**Comment by SeanLuke** [comment]
Haven't heard back since.  Hoping things are working; I can't seem to reproduce them.
