### ISSUE TITLE
Build fails on Linux

### ISSUE THREAD

**Issue by stu** [eclab/edisyn#44]
I went to build the jar but it seems to be missing a Librarian class. I dont know if this is on purpose so nobody can build it or not. Nothing in documentation that I could see.

**Comment by eclab** [comment]
Try now.

**Comment by stu** [comment]
Yep, works. I've modified the Makefile to make it a bit easier on myself. Issue is resolved for me.

[patch.txt](https://github.com/eclab/edisyn/files/7766491/patch.txt)
