### ISSUE TITLE
SSL certificate of edisyn.jar download can not be verified by curl

### ISSUE THREAD

**Issue by SpotlightKid** [eclab/edisyn#48]
I maintain the [edisyn-bin](https://aur.archlinux.org/packages/edisyn-bin) package in the Arch User Repository (AUR), which downloads and installs the provided [edisyn.jar](https://cs.gmu.edu/~eclab/projects/edisyn/edisyn.jar).

Since sometime recently, curl (which is used in the package build process by `makepkg` to download `edisyn.jar`) complains that it can not verify the SSL certificate of the server, which hosts this file (cs.gmu.edu). Thus the package build process can not proceed and *the package build fails*.

```
 curl -v -O https://cs.gmu.edu/~eclab/projects/edisyn/edisyn.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 129.174.125.139:443...
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to cs.gmu.edu (129.174.125.139) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [108 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [1735 bytes data]
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
} [2 bytes data]
* SSL certificate problem: unable to get local issuer certificate
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

It seems that this server is mis-configured, because it only sends part of the certificate chain:

[SSL Server Test for cs.gmu.edu](https://www.ssllabs.com/ssltest/analyze.html?d=cs.gmu.edu)

My suggestion would be to just host the `edisyn.jar` file elsewhere. For example, you could tag a version in Git (which would be *very helpful* in any case), create a release on Github for that tag and attach the JAR file to this release. This could all be done via the Github web interface, no local git needed (since you mentioned you use SVN locally).

**Comment by eclab** [comment]
I'm afraid Edisyn's binaries have to be hosted in this location for the foreseeable future, as it's the primary server for the computer science department in which I work, and for certain space reasons the binaries can't be hosted on github proper.  I must warn you that there's no guarantee that this location will be consistent or permanent, though I imagine it will be consistent for the time being.  I will mention to the powers that be that their SSL certificate has expired though.

**Comment by SpotlightKid** [comment]
Thanks for the explanation. This is unfortunate, though, since it means, that this binary distribution can not be packaged for Arch (and probably not for any other Linux distro either). I also cannot make a package, which builds from the sources for a particular release, simply because their is neither a source distribution archive, nor a git tag or anything, which identifies a certain state of the sources as a particular release. The best I can do is make a VCS AUR package, which builds the latest git version, whatever that is at a particular time.

**Comment by eclab** [comment]
GMU is confused by this.  They tell me that the certs for cs.gmu.edu <http://cs.gmu.edu/> and *.cs.gmu.edu <http://cs.gmu.edu/> were renewed this past October.  It is the case that the wildcard certificate for *.vse.gmu.edu <http://vse.gmu.edu/>, which points to the same machine, expired on 2/13 expired, and they've fixed this; but they do not know why this would affect curl.  At any rate, I just did the same curl test:

	curl -v -O https://cs.gmu.edu/~eclab/projects/edisyn/edisyn.jar <https://cs.gmu.edu/~eclab/projects/edisyn/edisyn.jar>

... and it seems to work fine; please verify.

**Comment by SpotlightKid** [comment]
The problem is not an expired certificate, it seems to be that the server does not send the intermediary certificates between the server cert and the root CA cert. If you direct the GMU team to the SSL server test I linked above, they should be able to identity the problem, I think.

The curl command you tried does not use HTTPS but HTTP, so issues with the cert will not manifest themselves there. :)

**Comment by SeanLuke** [comment]
Hmmm, the curl command was a cut and paste of what you had sent...

At any rate, here's what I got back from GMU's network team:

```
We've seen this on a few Linux boxes that connect via SSL/TLS to machines with a cert issued by InCommon (where all of GMU gets their certs issued). I'm not sure why the Linux distros don't get the same CA trust packages that the web browsers get. It can be fixed on the client side on a Red Hat/CentOS/Rocky/Alma linux distro by putting the attached file (which contains certs that connect the InCommon CA to a known trusted CA) in 

/etc/pki/ca-trust/source/anchors

and running the command

update-ca-trust
```

What do you think?

**Comment by SeanLuke** [comment]
I'm told by my admin team that they have added the InCommon intermediate certs to the trust chain for the server, and have replaced the SSL cert for cs.gmu.edu with a file that includes the intermediate certs.  It might patch things up.

**Comment by SpotlightKid** [comment]
> Hmmm, the curl command was a cut and paste of what you had sent...

I think you left out the `https://` part. 

> I'm told by my admin team that they have added the InCommon intermediate certs to the trust chain for the server,

Anyway, that fixed the issue.

Many thanks!
