### ISSUE TITLE
DSI Tetr4 not sending correct unison mode to synth

### ISSUE THREAD

**Issue by devicerCode** [eclab/edisyn#49]
If you are using a DSI Tetr4 and have the appropriate editor mode open, and you attempt to send a patch to the synth using "send to synth" or "write to patch" then it changes the unison mode if you have a unison patch selected. 

To replicate: 
1. Start Edisyn version 30 and a new prophet 08/mopho/tetra editor
2. Select [T] Tetr4 synth type
3. Make sure there's an audible basic patch loaded, or make one
4. Turn on unison
5. Select Unison mode "1 voice"
6. Send the patch through the "send to synth" drop down selector, or send it using "write to patch"
7. Play some notes and it will have made it "All voices detune 3" instead of "1 voice"

It seems to also change unison mode for any of the other modes apart from "All voices detune 3" so essentially always sends that mode as far as I can tell. 

Version: Edisyn 30, on windows 10.

**Comment by eclab** [comment]
What happens if you change step #5 to some other mode.  What does it get changed to then?  Can you give me mapping from what you set it to, to what it winds up as?  In the meantime, I'll look into it.

**Comment by eclab** [comment]
I think I might have spotted the bug.  Do you by any chance have Unison/Key Assign to "Last Note"?  That would trigger the "All Voices Detune 3" I'm guessing

**Comment by devicerCode** [comment]
Damn you're fast :D Yes, I do have "Last Note" as the selected value for Unison/Key Assign.

**Comment by eclab** [comment]
I think the code has Unison/Key Assign (which is, in sysex specs, called "Unison Key Mode") and Unison Mode (which is "Unison Mode") swapped in the order of parameters.

Send me email directly ***@***.***) and I'll send you a private beta to test out.

Sean

**Comment by eclab** [comment]
Looking into the real-time changes.  What happens if you make a setting on the Tetra, then request the current patch into Edisyn?  Does Edisyn update to the proper values?

**Comment by eclab** [comment]
Okay, I've found a problem: as verified a while back with Sequential, the positions for unison-mode and unison-key-mode are swapped in the documentation for the Prophet '08.  This means that, at least for the Prophet '08, the CURRENT version of Edisyn is correct for sending individual parameters via NRPN, for receiving them via NRPN, and for sending and receiving patch dumps.

You mentioned above that the current version appeared to be swapped for sending and receiving patch dumps on the tetra.  After I swapped them for you, it appeared that NRPN was now swapped on the tetra.  So what I need to know is:

For the CURRENT version of Edisyn, where are unison-mode and unison-key-mode swapped on the tetra:

* Sending individual parameters via NRPN 
* Receiving individual parameters via NRPN 
* Sending an entire patch to the synth
* Receiving an entire patch from the synth

I'm guessing it's just the last two.

**Comment by devicerCode** [comment]
So for the current - not-beta - one (version 30) then:

- Sending from editor: updates synth live, does so correctly for both unison key assign and unison mode
- receiving from synth into editor: changing single params on the synth updates the editor live, and does so correctly for both unison key assign and unison mode when they are setup as assignable params.
- Sending entire patch to the synth: seems to be swapped between unison key assign and unison mode
- Receiving entire patch from synth: seems to be swapped between unison key assign and unison mode

So yeah your guess seems correct. tested with a couple of values each on the latter 2, and was saving the patch each time on the synth before requesting it for the last one. an example: "last retrg" and "1 voice" on the tetra come out as "low note" and "all voices detune 3" in the editor.

**Comment by devicerCode** [comment]
Tetra.Beta2 seems to be all good, both send and receive for real time edits, and both send and receive for entire patches working as they should as best I can establish from a range of different values for both unison key assign, and unison mode parameters. Fixed in other words :)

**Comment by eclab** [comment]
Good to hear.  I hope the tweak I made for the Mopho Keyboard was also correct (and that the Mopho and Mopho XL didn't need it).  Feel free to use the beta for now (the P2K editor doesn't work yet).  I'll get the changes pushed out in the next version.
