### ISSUE TITLE
Send current patch only if patch was changed

### ISSUE THREAD

**Issue by gagarine** [eclab/edisyn#50]
I'm using this fun software with a microKorg. This is a feature request.

The microKorg do not support "Send real time change". I'm using "Repeatedly send to the current patch". But sadly this is not really practical as the current note stop each time the patch is send. You can change the speed by adapting the test note interval and length, but still not very practical.

But why send the patch if it wasn't edited? I think the best for my use case would be "Send to the current patch after each edit" option. If I click on something, once I release the mouse Edisyn send the patch. A sister options may be "Pause between test note -> Play a test note each time a patch is send" but personally I'm using the microKorg keys directly.

Thanks again for edisyn!

**Comment by SeanLuke** [comment]
The existing mechanism was a bandaid while I tried to think of an effective way to do exactly what you describe: send the entire patch, perhaps haltingly, after the user makes a modification to one parameter.  It's harder than it sounds for technical reasons, but I'll look into some way to try to get it working.  I'll leave this open in the meantime.

**Comment by SeanLuke** [comment]
Edisyn has been modified to include an "Auto Sends Patches" option.  If you select this, and your synthesizer cannot send individual parameters, then Edisyn will dump the entire patch in lieu of a single parameter.  Hopefully it'll make working on the MicroKorg more tolerable.
