### ISSUE TITLE
Missing Pitch Envelope Sustain Level slider in D-110 editor

### ISSUE THREAD

**Issue by 02FD** [eclab/edisyn#53]
The D-110 editor is missing the Sustain slider in the pitch envelope settings. It will always write 0x00, which corresponds to a level of -50.

This leads me to conclude that the editor was tested with a D-10, instead of a D-110, which probably eased accessing the parameters. The D-10 (according to the midi implementation) has a "dummy" value where the D-110 would have the sustain level. To maintain compatibility between both, it'd be best to write a value of 0x32 instead of 0x00, or include a slider for it that wouldn't affect the D-10 anyway.

**Comment by 02FD** [comment]
Oops. I pressed some buttons. Not familiar with github yet.

Anyway, yes, I'll get on that email.

**Comment by SeanLuke** [comment]
Per offline discussion, I've committed changes to include this parameter and things appear to be working, so closing.  Changes will appear in the next release.
