### ISSUE TITLE
Breath Control target Cutoff TX81Z

### ISSUE THREAD

**Issue by MrDevDevy** [eclab/edisyn#56]
I am trying to get the breath control from an EWI device to control the cutoff of a patch, is this possible? 

*edit* I am able to target the volume now. I just need to target the cutoff.

**Comment by SeanLuke** [comment]
I'm afraid I can't answer that question.

**Comment by SeanLuke** [comment]
If by cutoff you mean the filter cutoff: the TX81Z doesn't have a filter.
