### ISSUE TITLE
workflow with K1

### ISSUE THREAD

**Issue by severak** [eclab/edisyn#57]
Hi. How I am supposed to use this program with my K1 keyboard?

I tested it and it seems to work - old presets can be downloaded from unit and new presets can be uploaded. But the process of uploading new ones is somewhat janky and I don't understand what I am supposed to do. Do I need to "Send to current patch" after each edit or to switch tones after each change on synth itself?

**Comment by eclab** [comment]
Your K1 has two kinds of memory:

- Permanent patch storage. This is where your patches reside.

- Temporary working memory.  This is where the patch that you are *currently playing* has its parameters.  When you power cycle the machine, this is erased.

When you change a patch on your synth, it is copied from permanent patch storage into temporary working memory, erasing the old patch currently in temporary working memory.  When you save a patch on the K1, it is copied from temporary working memory to permanent patch storage, erasing the old patch presently located wherever you saved it.

Edisyn can do the following:

1. REQUEST a patch.  This asks the K1 to load the patch into your temporary working memory and then give the patch to Edisyn.

2. WRITE a patch.  This writes Edisyn's patch to permanent patch storage.  It also loads it into temporary working memory.

3. SEND a patch.  This just writes Edisyn's patch to temporary working memory so you can play it and hear it. It doesn't save it to patch storage.

4. CHANGE A PARAMETER IN REAL TIME.  When you change a parameter in Edisyn, it tries to also change that one parameter in your machine's temporary working memory so you can hear what the change did.

5. SAVE a patch to DISK

6. LOAD one or more patches from DISK

And there's also librarian features.  On the K1 there's one thing Edisyn can't do that it can do on other synths: you can't REQUEST a patch directly from current memory.

Lots of things Edisyn does automatically SEND patches: undo/redo, morphing, randomization, etc., etc.  And you can of course SEND manually.

If you have "sends real-time changes" turned on, then you probably don't need to send to current patch after each edit; but you could if you liked.  Remember this just sends to temporary memory -- if you want the patch to be *permanently stored* you need to WRITE it.

**Comment by severak** [comment]
This helped me a lot and now I am able to edit patches in real time. Thanks a lot.

**Comment by SeanLuke** [comment]
NP
