### ISSUE TITLE
Plans for Mac support?

### ISSUE THREAD

**Issue by naturligasteg** [eclab/edisyn#58]
Hello.

I found this program and it looks great, but since I am on a Mac M1 I red your lines about Mac support. Got any plans about getting an M1 or getting it officially supported for Mac?

**Comment by esaruoho** [comment]
@eclab what is in theory required for this? i have a m1 mac, could i attempt to build it locally?

**Comment by eclab** [comment]
You could build it locally: I could also probably build it in the next release as well.  Building is pretty simple if you have Java and the XCode command tools installed.  However it's not a big deal to be honest, the intel version runs pretty well under Rosetta.

Sean

**Comment by SeanLuke** [comment]
For the time being, I'm going to close this issue but if you feel the need to reopen it, go ahead.
