### ISSUE TITLE
Unable to extract ZIP

### ISSUE THREAD

**Issue by Disgraceland** [eclab/edisyn#6]
Hi Sean,

Native archive app renames the zip with a .cpgz extension. (It did  this with the last build).
Keka exists with an error type 2.

I did run a permissions re-set on the file to see if it helped - unfortunately not.
Cheers
John

**Comment by Disgraceland** [comment]
Ah - zip file is only 46k when I download... :)

**Comment by Disgraceland** [comment]
Ok - The link to the DL on  the homepage works fine -.

If I go into the install folder and Save As, I get a 43k file.

V odd!!

**Comment by eclab** [comment]
Probably made a mistake on upload. Gimme a few hours.On Mar 10, 2018 3:01 PM, Disgraceland <notifications@github.com> wrote:Ok - The link to the DL on  the homepage works fine -.
If I go into the install folder and Save As, I get a 43k file.
V odd!!

**Comment by eclab** [comment]
> If I go into the install folder and Save As, I get a 43k file.

This is because the install folder link isn't to the file -- it's to the Github page which *contains* the file.  You click on that link, then you click "View Raw".  Moral of the story: use the direct link from the homepage.

**Comment by Disgraceland** [comment]
Aha!
And in true IT style, rather than DL an HTML page which would maybe alert people to this fact... it downloads as a Zip :)
