### ISSUE TITLE
Can outside contributors add support for new synths?

### ISSUE THREAD

**Issue by hikari-no-yume** [eclab/edisyn#72]
Hi, I'm wondering if you're interested in contributions to add support for more synths. I understand you're not willing to add support yourself for a synth you don't own, but how do you feel about another contributor adding support for a synth that *they* own?

**Comment by eclab** [comment]
That'd be great!  In fact there are a few examples, for example the Rev2 editor.  I'd be glad to offer suggestions or help to the degree I can (this year I'm 5000 miles from my synths, so I am somewhat limited in that respect).

**Comment by hikari-no-yume** [comment]
Thanks for the response! I'll at least consider contributing then. I'm currently not sure as to whether I want to write my own tool for the synths that interest me, or whether I'll contribute support to Edisyn.

**Comment by eclab** [comment]
I fully support making your own software!  But if you'd like to add to Edisyn, I'd be glad to help out.  Which synths were you thinking of?

**Comment by hikari-no-yume** [comment]
Various Roland GS and Yamaha XG ROMplers basically. Those aren't fully editable synths but there's quite a lot of customisation available via special SysEx and CC messages. For example the reverb/chorus/variation effect parameters and the A/D/R envelopes for instrument voices can be modified.

**Comment by eclab** [comment]
Interesting!  I had shied away from GM/XG synths in general because a great many of them can't save their patches.  The synth on the Yamaha QY series was particularly frustrating in this regard.  Would be interested in how far you got.

**Comment by hikari-no-yume** [comment]
I ended up making my own tool: https://github.com/hikari-no-yume/SoundPalette. I hope it's interesting!

**Comment by eclab** [comment]
It looks fun and useful.  I wish you the best with it!
