### ISSUE TITLE
Any plan to support Yamaha DX7II ?

### ISSUE THREAD

**Issue by solyarisoftware** [eclab/edisyn#77]
Hi Sean, 
I just discovered your beautiful librarian.

I would like to load my DX7II  banks (full dump) sysex files (with the goal of splitting a performance in 2 DX7 voices and so play my old patches with some software emulator, see: https://github.com/bladeSk/DX7II-Librarian/issues/4 ) , but as far as I understand ( I installed and ruin edisyn) currently there is no way to manage DX7II sysex files. That's correct?

If so, there is any plan to include DX7II? 

Thanks
giorgio

**Comment by eclab** [comment]
I will not be able to make a DX7 II patch editor unless I acquire, or other wise get a long-term loan, of a DX7 II!

I suspect that you might be in Italy.  I am currently in Milan.  Feel free to contact me directly at ***@***.***

>
