### ISSUE TITLE
Waldorf M fw 1.10 support

### ISSUE THREAD

**Issue by rydan** [eclab/edisyn#80]
Would be nice to have support for the digital filter extra modulation routings (and the new oscillator modes) from FW 1.10.

**Comment by eclab** [comment]
It'll have to wait -- I have not received sysex information from Vlad on this yet.

**Comment by rydan** [comment]
I see. Will just have to wait then...

**Comment by eclab** [comment]
Vladis has indicated sysex documentation in his next release -- no direct information to me yet, but here's hoping.  I'll close this for now.
