### ISSUE TITLE
Lock sections for randomisation

### ISSUE THREAD

**Issue by hubweil** [eclab/edisyn#88]
it would be great, if it was possible to lock parameters to exclude them from randomization. (i use it for the WALDORF M )
thank you  for all your work!

**Comment by eclab** [comment]
You absolutely can!  Look at the bottom of the Edit menu: see stuff like "Edit Mutation Parameters".

**Comment by hubweil** [comment]
thank you - i am really stupid sometimes;)

**Comment by hubweil** [comment]
can i ask one more thing: why is the wavetable count in the editor one less than on the synth itself? like, on the editor it is 51 and on the synth 52 for example. thank you again!

**Comment by eclab** [comment]
Could you be more specific?  The M has 96 wavetables:  00 Resonant through 95 3V Haus Organ.

**Comment by hubweil** [comment]
sure, i made photos, maybe they show better 
![20241115_223158](https://github.com/user-attachments/assets/6b53702d-ac04-4149-9940-4c6f5a2be107)
![20241115_223209](https://github.com/user-attachments/assets/6008a53d-be6b-47b9-a8cd-93502d19f003)
![20241115_223222](https://github.com/user-attachments/assets/b87ebc8f-b61f-48ba-8280-cea872b03b65)

**Comment by eclab** [comment]
This might be a one-off error, possibly a stupidity on my part or possibly caused by a recent change in the firmware.  What firmware version are you using? On your M, can you change the wavetable to Wavetable 0?  Or is Wavetable 1 the lowest possible wavetable, and is it "Resonant"?

**Comment by hubweil** [comment]
Edisyn is the latest version, M is on latest versions and my (factory) wavetable count is from 1 RESONANT to 96 HAUSORGAN

**Comment by eclab** [comment]
Fixed. The revision will be out in the next version of Edisyn.

**Comment by hubweil** [comment]
thank you!
