### ISSUE TITLE
Dowload links don't work

### ISSUE THREAD

**Issue by alex-zender** [eclab/edisyn#89]
Dowload links don't work (((
<img width="222" alt="Снимок экрана 2024-11-22 в 12 38 24" src="https://github.com/user-attachments/assets/fe3a413c-1cd3-4b21-a4e3-0793914a039c">

**Comment by eclab** [comment]
They're working for me.  Could have been a temporary issue?

**Comment by alex-zender** [comment]
> They're working for me.  Could have been a temporary issue?

My friends also can't download.

**Comment by markusschloesser** [comment]
Tested osx and windows download, both working fine for me

**Comment by noelvd** [comment]
Works fine here as well. Download took only about 30 sec. :)

**Comment by eclab** [comment]
Lacking further information, I think it's reasonable to close this thread.
