### ISSUE TITLE
Support for remote control via TouchOSC

### ISSUE THREAD

**Issue by dbogdanov** [eclab/edisyn#9]
It would be great to have support for remote control on tablets, for example via TouchOSC, or similar mobile apps. Is that technically feasible?

**Comment by eclab** [comment]
Edisyn is written in Java using Swing.  It could only run on tablets that support this: for example perhaps windows tablets.

Sean

**Comment by dbogdanov** [comment]
I guess what I meant was if there is a way one could interface with a PC running Edisyn. I guess that's what Midiquest does. The TouchOSC app on a tablet serves to control the main application on the PC, that in turn controls a synth.

**Comment by eclab** [comment]
Ah, I got it.  Actually, Edisyn is already set up to do this, but you'll have to do some work first.  Under the Map menu, you can do absolute CC, absolute NRPN, and relative CC mapping for any of the widgets.  So hook up TouchOSC, set it up as Edisyn's controller via MIDI->ChangeMidi, and start mapping  CC or NRPN on TouchOSC to widgets in your desired Edisyn patch editor.  Then you should be able to control Edisyn from TouchOSC.

Edisyn doesn't support OSC right now.  I'm not sure it ever will given that MIDI 2.0 is coming out and will probably moot it.

Sean

**Comment by dbogdanov** [comment]
Got it, thank you for this explanation! I am now doing some test mappings for Kawai K1. It appears there is a very large latency (few seconds) with which mapped Edisyn widgets follow controls on TouchOSC. Other applications (Ableton Live) react instantaneously.

**Comment by eclab** [comment]
> On Dec 12, 2018, at 8:35 PM, Dmitry Bogdanov <notifications@github.com> wrote:
> 
> Got it, thank you for this explanation! I am now doing some test mappings for Kawai K1. It appears there is a very large latency (few seconds) with which mapped Edisyn widgets follow controls on TouchOSC. Other applications (Ableton Live) react instantaneously.

I just double-checked and Edisyn is responding immediately and cleanly to incoming CC messages mapped to its widgets (using the K1 patch editor) -- using a Novation Zero Mk II over USB.  This tells me that there is likely something else going on in your arrangent.  Some kind of routing problem?  I'm running OS X.

**Comment by dbogdanov** [comment]
I was using TouchOSC over WiFi. I've tested with another controller over USB (Arturia Keystep) and I get exactly the same issue. Both controllers work without any lag in Ableton. MacOS High Sierra. I have no idea how to debug this. Could it be that the lag is due to Java?

**Comment by dbogdanov** [comment]
Thank you for your suggestions!! I've been able to locate the issue. The controls react instantly when disabling MIDI -> Send Real Time Changes. I thought that I should have also worked when enabled. Any related problem there?

**Comment by eclab** [comment]
At first I thought the issue was that the K1 has very, very slow sysex and Edisyn is forced to put a significant delay between real-time changes.  But now I don't think that's the issue -- when I have Send Real Time Changes turned on, it's pretty responsive.  I'd guess you've got a loop.  When you do MIDI -> Change MIDI, what are the devices chosen for "Receive From", "Send To", and "Controller"?

**Comment by dbogdanov** [comment]
I've set up "Receive From" and "Send To" to IAC Driver IAC Bus 1 and 2, and "Controller" to Arturia KeyStep 32. It lags to the point of getting a spinning wheel from time to time.

**Comment by dbogdanov** [comment]
I've set up "Receive From" and "Send To" to IAC Driver IAC Bus 1 and 2, and "Controller" to Arturia KeyStep 32. It lags to the point of getting a spinning wheel from time to time.

**Comment by dbogdanov** [comment]
Any idea how to narrow down the problem?

**Comment by eclab** [comment]
Let's simplify things for the moment.

- Set the Controller to None.
- Receive From IAC Bus 1
- Send To IAC Bus 2
- Nothing at all the other end of IAC Bus 1 or 2 (no DAW, no controller or program).
- Kawai K1 patch editor
- Sends Real Time Changes -> TRUE

With this configuration I can change any widget in real time with no delay whatsoever.  I'm running OS X 10.3.6 on a Macbook Pro. Java 1.8.

If you're having a spinning wheel in this configuation: (1) what steps will reliably reproduce it? (2) Are you getting any error messages -- java exceptions for example -- produced at the end of /var/log/system.log ?

**Comment by dbogdanov** [comment]
```
- Set the Controller to None. 
- Receive From IAC Bus 1 
- Send To IAC Bus 2 
- Nothing at all the other end of IAC Bus 1 or 2 (no DAW, no controller or program). 
- Kawai K1 patch editor 
- Sends Real Time Changes -> TRUE
```

This configuration without controller works fine. The delays occur only when using a controller.

**Comment by eclab** [comment]
Okay, next step.  Download MidiKeys (http://www.manyetas.com/creed/midikeys.html).  Launch it and set it to be the Controller in Edisyn.  Does the problem manifest itself?

**Comment by SeanLuke** [comment]
Lacking further response, I'm going to close this for now.
